[package]
name = "custom"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
actix-web = {version = "4.9.0", features = ["default"]}
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
#futures = "0.3.31"